version: '3.7'

services:
  rest:
    image: duckdbrest
    ports:
      - "1294:1294"

  gotty:
    image: duckdbrest
    ports:
      - "8080:1294"
    command: sh -c "gotty --port ${PORT:-1294} --permit-write --reconnect duckdb -interactive myduck.db -readonly"
    environment:
      - MC_HOST_ducks3=http://minioadmin:minioadmin@minio:9000
    volumes:
      - ./init.sql:/data/init.sql

  bashapi:
    image: duckdbrest
    ports:
      - "8181:8181"
    command: bash -c "cd /bash-cli-api && DDB_PATH=/data/myduck.db ./index.sh"

  sherver:
    image: duckdbrest
    ports:
      - "8282:8282"
    command: bash -c "cd /sherver && ./sherver.sh 8282 2> /proc/1/fd/1"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./s3:/data
